// Package vmclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package vmclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Oauth2Scopes oauth2ContextKey = "oauth2.Scopes"
)

// Defines values for PowerState.
const (
	PowerStateOff       PowerState = "Off"
	PowerStateOn        PowerState = "On"
	PowerStateSuspended PowerState = "Suspended"
	PowerStateUnknown   PowerState = "Unknown"
)

// Valid indicates whether the value is a known member of the PowerState enum.
func (e PowerState) Valid() bool {
	switch e {
	case PowerStateOff:
		return true
	case PowerStateOn:
		return true
	case PowerStateSuspended:
		return true
	case PowerStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ProxmoxVmType.
const (
	LXC  ProxmoxVmType = "LXC"
	QEMU ProxmoxVmType = "QEMU"
)

// Valid indicates whether the value is a known member of the ProxmoxVmType enum.
func (e ProxmoxVmType) Valid() bool {
	switch e {
	case LXC:
		return true
	case QEMU:
		return true
	default:
		return false
	}
}

// Defines values for VmType.
const (
	VmTypeAzure   VmType = "Azure"
	VmTypeProxmox VmType = "Proxmox"
	VmTypeUnknown VmType = "Unknown"
	VmTypeVsphere VmType = "Vsphere"
)

// Valid indicates whether the value is a known member of the VmType enum.
func (e VmType) Valid() bool {
	switch e {
	case VmTypeAzure:
		return true
	case VmTypeProxmox:
		return true
	case VmTypeUnknown:
		return true
	case VmTypeVsphere:
		return true
	default:
		return false
	}
}

// ConsoleConnectionInfo defines model for ConsoleConnectionInfo.
type ConsoleConnectionInfo struct {
	// Hostname The hostname or address to use to connect
	Hostname *string `json:"hostname,omitempty"`

	// Password The optional password to use to connect
	// If omitted, the user will be prompted on connection
	// Note: This must be set to connect to a Windows machine using Network Level Authentication
	Password *string `json:"password,omitempty"`

	// Port The port to use to connect
	Port *string `json:"port,omitempty"`

	// Protocol The protocol to use to connect, such as rdp, ssh, etc
	Protocol *string `json:"protocol,omitempty"`

	// Username The optional username to use to connect
	// If omitted, the user will be prompted on connection
	// Note: This must be set to connect to a Windows machine using Network Level Authentication
	Username *string `json:"username,omitempty"`
}

// PowerState defines model for PowerState.
type PowerState string

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail               *string                `json:"detail,omitempty"`
	Instance             *string                `json:"instance,omitempty"`
	Status               *int32                 `json:"status,omitempty"`
	Title                *string                `json:"title,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProxmoxVmInfo defines model for ProxmoxVmInfo.
type ProxmoxVmInfo struct {
	// Id The unique integer Id of the VM in Proxmox
	Id *int32 `json:"id,omitempty"`

	// Node The node that this VM is currently running on
	Node *string        `json:"node,omitempty"`
	Type *ProxmoxVmType `json:"type,omitempty"`
}

// ProxmoxVmType defines model for ProxmoxVmType.
type ProxmoxVmType string

// Vm defines model for Vm.
type Vm struct {
	ConsoleConnectionInfo *ConsoleConnectionInfo `json:"consoleConnectionInfo,omitempty"`

	// DefaultUrl True if this VM's Url has not been explicitly set and a default value has been computed
	DefaultUrl *bool `json:"defaultUrl,omitempty"`

	// Embeddable If false, only allow opening this VM in a new tab
	Embeddable *bool `json:"embeddable,omitempty"`

	// HasPendingTasks True if this Vm currently has pending tasks (power on, power off, etc)
	HasPendingTasks *bool `json:"hasPendingTasks,omitempty"`

	// HasSnapshot True if this VM has at least one snapshot. Currently Supported for Vsphere only.
	HasSnapshot *bool `json:"hasSnapshot,omitempty"`

	// Id Virtual Machine unique id
	Id *openapi_types.UUID `json:"id,omitempty"`

	// IpAddresses A list of IP addresses of the Vm
	IpAddresses *[]string `json:"ipAddresses,omitempty"`

	// Name The Vm's name
	Name          *string        `json:"name,omitempty"`
	PowerState    *PowerState    `json:"powerState,omitempty"`
	ProxmoxVmInfo *ProxmoxVmInfo `json:"proxmoxVmInfo,omitempty"`

	// TeamIds The Ids of the Team's the Vm is a part of
	TeamIds *[]openapi_types.UUID `json:"teamIds,omitempty"`
	Type    *VmType               `json:"type,omitempty"`

	// Url Url to the Vm's console
	Url *string `json:"url,omitempty"`

	// UserId Id of the Vm's owner if it is a personal Vm
	UserId *openapi_types.UUID `json:"userId,omitempty"`
}

// VmCreateForm defines model for VmCreateForm.
type VmCreateForm struct {
	ConsoleConnectionInfo *ConsoleConnectionInfo `json:"consoleConnectionInfo,omitempty"`

	// Embeddable If false, only allow opening this VM in a new tab
	Embeddable    *bool                `json:"embeddable,omitempty"`
	Id            *openapi_types.UUID  `json:"id,omitempty"`
	Name          string               `json:"name"`
	ProxmoxVmInfo *ProxmoxVmInfo       `json:"proxmoxVmInfo,omitempty"`
	TeamIds       []openapi_types.UUID `json:"teamIds"`
	Url           *string              `json:"url,omitempty"`
	UserId        *openapi_types.UUID  `json:"userId,omitempty"`
}

// VmType defines model for VmType.
type VmType string

// VmUpdateForm defines model for VmUpdateForm.
type VmUpdateForm struct {
	ConsoleConnectionInfo *ConsoleConnectionInfo `json:"consoleConnectionInfo,omitempty"`

	// Embeddable If false, only allow opening this VM in a new tab
	Embeddable    *bool               `json:"embeddable,omitempty"`
	Name          string              `json:"name"`
	ProxmoxVmInfo *ProxmoxVmInfo      `json:"proxmoxVmInfo,omitempty"`
	Url           *string             `json:"url,omitempty"`
	UserId        *openapi_types.UUID `json:"userId,omitempty"`
}

// oauth2ContextKey is the context key for oauth2 security scheme
type oauth2ContextKey string

// CreateVmApplicationWildcardPlusJSONRequestBody defines body for CreateVm for application/*+json ContentType.
type CreateVmApplicationWildcardPlusJSONRequestBody = VmCreateForm

// CreateVmJSONRequestBody defines body for CreateVm for application/json ContentType.
type CreateVmJSONRequestBody = VmCreateForm

// UpdateVmApplicationWildcardPlusJSONRequestBody defines body for UpdateVm for application/*+json ContentType.
type UpdateVmApplicationWildcardPlusJSONRequestBody = VmUpdateForm

// UpdateVmJSONRequestBody defines body for UpdateVm for application/json ContentType.
type UpdateVmJSONRequestBody = VmUpdateForm

// Getter for additional properties for ProblemDetails. Returns the specified
// element and whether it was found
func (a ProblemDetails) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetails
func (a *ProblemDetails) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a *ProblemDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a ProblemDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RemoveVmFromTeam request
	RemoveVmFromTeam(ctx context.Context, teamId openapi_types.UUID, vmId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddVmToTeam request
	AddVmToTeam(ctx context.Context, teamId openapi_types.UUID, vmId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateVmWithBody request with any body
	CreateVmWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateVmWithApplicationWildcardPlusJSONBody(ctx context.Context, body CreateVmApplicationWildcardPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateVm(ctx context.Context, body CreateVmJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteVm request
	DeleteVm(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVm request
	GetVm(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateVmWithBody request with any body
	UpdateVmWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateVmWithApplicationWildcardPlusJSONBody(ctx context.Context, id openapi_types.UUID, body UpdateVmApplicationWildcardPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateVm(ctx context.Context, id openapi_types.UUID, body UpdateVmJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RemoveVmFromTeam(ctx context.Context, teamId openapi_types.UUID, vmId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRemoveVmFromTeamRequest(c.Server, teamId, vmId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddVmToTeam(ctx context.Context, teamId openapi_types.UUID, vmId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddVmToTeamRequest(c.Server, teamId, vmId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateVmWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateVmRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateVmWithApplicationWildcardPlusJSONBody(ctx context.Context, body CreateVmApplicationWildcardPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateVmRequestWithApplicationWildcardPlusJSONBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateVm(ctx context.Context, body CreateVmJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateVmRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteVm(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteVmRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVm(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVmRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateVmWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateVmRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateVmWithApplicationWildcardPlusJSONBody(ctx context.Context, id openapi_types.UUID, body UpdateVmApplicationWildcardPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateVmRequestWithApplicationWildcardPlusJSONBody(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateVm(ctx context.Context, id openapi_types.UUID, body UpdateVmJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateVmRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRemoveVmFromTeamRequest generates requests for RemoveVmFromTeam
func NewRemoveVmFromTeamRequest(server string, teamId openapi_types.UUID, vmId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "teamId", teamId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "vmId", vmId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/teams/%s/vms/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddVmToTeamRequest generates requests for AddVmToTeam
func NewAddVmToTeamRequest(server string, teamId openapi_types.UUID, vmId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "teamId", teamId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "vmId", vmId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/teams/%s/vms/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateVmRequestWithApplicationWildcardPlusJSONBody calls the generic CreateVm builder with application/*+json body
func NewCreateVmRequestWithApplicationWildcardPlusJSONBody(server string, body CreateVmApplicationWildcardPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateVmRequestWithBody(server, "application/*+json", bodyReader)
}

// NewCreateVmRequest calls the generic CreateVm builder with application/json body
func NewCreateVmRequest(server string, body CreateVmJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateVmRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateVmRequestWithBody generates requests for CreateVm with any type of body
func NewCreateVmRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/vms")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteVmRequest generates requests for DeleteVm
func NewDeleteVmRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/vms/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetVmRequest generates requests for GetVm
func NewGetVmRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/vms/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateVmRequestWithApplicationWildcardPlusJSONBody calls the generic UpdateVm builder with application/*+json body
func NewUpdateVmRequestWithApplicationWildcardPlusJSONBody(server string, id openapi_types.UUID, body UpdateVmApplicationWildcardPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateVmRequestWithBody(server, id, "application/*+json", bodyReader)
}

// NewUpdateVmRequest calls the generic UpdateVm builder with application/json body
func NewUpdateVmRequest(server string, id openapi_types.UUID, body UpdateVmJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateVmRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateVmRequestWithBody generates requests for UpdateVm with any type of body
func NewUpdateVmRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/vms/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RemoveVmFromTeamWithResponse request
	RemoveVmFromTeamWithResponse(ctx context.Context, teamId openapi_types.UUID, vmId openapi_types.UUID, reqEditors ...RequestEditorFn) (*RemoveVmFromTeamResponse, error)

	// AddVmToTeamWithResponse request
	AddVmToTeamWithResponse(ctx context.Context, teamId openapi_types.UUID, vmId openapi_types.UUID, reqEditors ...RequestEditorFn) (*AddVmToTeamResponse, error)

	// CreateVmWithBodyWithResponse request with any body
	CreateVmWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateVmResponse, error)

	CreateVmWithApplicationWildcardPlusJSONBodyWithResponse(ctx context.Context, body CreateVmApplicationWildcardPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateVmResponse, error)

	CreateVmWithResponse(ctx context.Context, body CreateVmJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateVmResponse, error)

	// DeleteVmWithResponse request
	DeleteVmWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteVmResponse, error)

	// GetVmWithResponse request
	GetVmWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetVmResponse, error)

	// UpdateVmWithBodyWithResponse request with any body
	UpdateVmWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateVmResponse, error)

	UpdateVmWithApplicationWildcardPlusJSONBodyWithResponse(ctx context.Context, id openapi_types.UUID, body UpdateVmApplicationWildcardPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateVmResponse, error)

	UpdateVmWithResponse(ctx context.Context, id openapi_types.UUID, body UpdateVmJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateVmResponse, error)
}

type RemoveVmFromTeamResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r RemoveVmFromTeamResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RemoveVmFromTeamResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RemoveVmFromTeamResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AddVmToTeamResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r AddVmToTeamResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddVmToTeamResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AddVmToTeamResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateVmResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Vm
	JSONDefault  *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r CreateVmResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateVmResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateVmResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteVmResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r DeleteVmResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteVmResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteVmResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetVmResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Vm
	JSON404      *Vm
	JSONDefault  *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetVmResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVmResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetVmResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateVmResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Vm
	JSONDefault  *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r UpdateVmResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateVmResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateVmResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// RemoveVmFromTeamWithResponse request returning *RemoveVmFromTeamResponse
func (c *ClientWithResponses) RemoveVmFromTeamWithResponse(ctx context.Context, teamId openapi_types.UUID, vmId openapi_types.UUID, reqEditors ...RequestEditorFn) (*RemoveVmFromTeamResponse, error) {
	rsp, err := c.RemoveVmFromTeam(ctx, teamId, vmId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRemoveVmFromTeamResponse(rsp)
}

// AddVmToTeamWithResponse request returning *AddVmToTeamResponse
func (c *ClientWithResponses) AddVmToTeamWithResponse(ctx context.Context, teamId openapi_types.UUID, vmId openapi_types.UUID, reqEditors ...RequestEditorFn) (*AddVmToTeamResponse, error) {
	rsp, err := c.AddVmToTeam(ctx, teamId, vmId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddVmToTeamResponse(rsp)
}

// CreateVmWithBodyWithResponse request with arbitrary body returning *CreateVmResponse
func (c *ClientWithResponses) CreateVmWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateVmResponse, error) {
	rsp, err := c.CreateVmWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateVmResponse(rsp)
}

func (c *ClientWithResponses) CreateVmWithApplicationWildcardPlusJSONBodyWithResponse(ctx context.Context, body CreateVmApplicationWildcardPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateVmResponse, error) {
	rsp, err := c.CreateVmWithApplicationWildcardPlusJSONBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateVmResponse(rsp)
}

func (c *ClientWithResponses) CreateVmWithResponse(ctx context.Context, body CreateVmJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateVmResponse, error) {
	rsp, err := c.CreateVm(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateVmResponse(rsp)
}

// DeleteVmWithResponse request returning *DeleteVmResponse
func (c *ClientWithResponses) DeleteVmWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteVmResponse, error) {
	rsp, err := c.DeleteVm(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteVmResponse(rsp)
}

// GetVmWithResponse request returning *GetVmResponse
func (c *ClientWithResponses) GetVmWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetVmResponse, error) {
	rsp, err := c.GetVm(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVmResponse(rsp)
}

// UpdateVmWithBodyWithResponse request with arbitrary body returning *UpdateVmResponse
func (c *ClientWithResponses) UpdateVmWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateVmResponse, error) {
	rsp, err := c.UpdateVmWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateVmResponse(rsp)
}

func (c *ClientWithResponses) UpdateVmWithApplicationWildcardPlusJSONBodyWithResponse(ctx context.Context, id openapi_types.UUID, body UpdateVmApplicationWildcardPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateVmResponse, error) {
	rsp, err := c.UpdateVmWithApplicationWildcardPlusJSONBody(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateVmResponse(rsp)
}

func (c *ClientWithResponses) UpdateVmWithResponse(ctx context.Context, id openapi_types.UUID, body UpdateVmJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateVmResponse, error) {
	rsp, err := c.UpdateVm(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateVmResponse(rsp)
}

// ParseRemoveVmFromTeamResponse parses an HTTP response from a RemoveVmFromTeamWithResponse call
func ParseRemoveVmFromTeamResponse(rsp *http.Response) (*RemoveVmFromTeamResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RemoveVmFromTeamResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseAddVmToTeamResponse parses an HTTP response from a AddVmToTeamWithResponse call
func ParseAddVmToTeamResponse(rsp *http.Response) (*AddVmToTeamResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddVmToTeamResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateVmResponse parses an HTTP response from a CreateVmWithResponse call
func ParseCreateVmResponse(rsp *http.Response) (*CreateVmResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateVmResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Vm
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	case rsp.StatusCode == 201:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}

// ParseDeleteVmResponse parses an HTTP response from a DeleteVmWithResponse call
func ParseDeleteVmResponse(rsp *http.Response) (*DeleteVmResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteVmResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetVmResponse parses an HTTP response from a GetVmWithResponse call
func ParseGetVmResponse(rsp *http.Response) (*GetVmResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVmResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Vm
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Vm
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	case rsp.StatusCode == 200:
	// Content-type (text/plain) unsupported

	case rsp.StatusCode == 404:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}

// ParseUpdateVmResponse parses an HTTP response from a UpdateVmWithResponse call
func ParseUpdateVmResponse(rsp *http.Response) (*UpdateVmResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateVmResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Vm
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	case rsp.StatusCode == 200:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}
